version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  fbw_api:
    build: .
    image: fbw-api:latest
    container_name: fbw_api
    restart: unless-stopped
    expose:
      - 5000
